### ISSUE TITLE
Fix mistakes from Sprint 1, plus new deliverables for sprint 2

### ISSUE THREAD

**Issue by obonobo** [serum-390/soen390-team16-godzilla#112]
# 2. What you need to improve

## 2.1. General
* [x] _**No list of chosen User stories and Backlogs. If the user stories are the issues in Github, they are not following the template**_
* [x] Table of contents in documents didn’t have bookmarks (Some docs didn’t have ToC)

## 2.2. SAD
* [x] Blurry images (should be replaced by vectorized shapes whenever you can)
* [x] Should split Concern–Stakeholder Traceability table to a separated landscape page
* [x] _**Errors in section numbers**_
* [x] _**No page number**_
* [x] _**Why 3.10 Sources on page 24?**_
* [x] Didn’t mention the View model used in this SAD (is it 4+1 View model of Architecture?)
* [x] _**Class diagram on page 26 didn’t follow the clarified notation.**_
    - [x] Make a class diagram based on the domain model
* [x] _**The diagrams don't have a name and description or explanation.**_
* [x]  _**Misunderstanding the Logical View.**_ [Ref](http://web.ist.utl.pt/~fabio.ferreira/material/as/4+1view-architecture.pdf)
* [x] _**The package in the diagram of the Development view aren’t connected?**_
* [x] Should split the sequence diagram in the Process view into smaller diagrams

## 2.3. Risk management plan
* [x]  4 versions `1.0`?
* [x] Tables format

## 2.4. Testing plan
* [x] The document format is not consistent
* [x] _**No mention of coverage of Unit tests?**_

## 2.5. Release plan
* [x] Incomplete sprint 2 planning

## 2.6. Source code
* [x] The repo isn’t renamed as requested by PO

# 3. Marks
* [x] User Stories Backlog: completeness, meaningfulness, respect to format/conventions
* [x] Software Architecture: completeness of Domain Model, Component diagram

**Comment by obonobo** [comment]
# New deliverables for Sprint 2

- [ ] Defects tracking report
- [ ] Release plan for sprint 3
- [ ] UI modeling
- [ ] Updated deliverables
    - [ ] SAD
    - [ ] USB
    - [ ] RMP
    - [ ] Testing Plan
