### ISSUE TITLE
SPRINT 4: mega-todo - most important things to do for sprint 4

### ISSUE THREAD

**Issue by obonobo** [serum-390/soen390-team16-godzilla#181]
## Summary

As per the TA meeting ([see discord announcement](https://discord.com/channels/798634585059622974/798657183985303553/824008675323674634)), we have a full plate of stuff to work on for Sprint 4, including delivering core features, various fixes/corrections, additions to the SAD, and more.

## TODO

- [ ] Important : We need to implement Quality management , Transportation planning , Access levels, vendor/customer management, accounting  features for this sprint. I'll work on the transportation planning. 
- [ ] He sent a screenshot of code in slack and mentioned that we need to pay more attention to coding conventions for this sprint
- [ ] He mentioned that we have not fixed some issues in the SAD from sprint 2 and we will lose mark if we don't do so for the next sprint
- [ ] Quality management feature : must be integrated with items and don't need a separate page. different quality bikes have different prices, there should be a way to notify the system of items that have quality below accepted
- [ ] We should implement send emails according to events. He mentioned "sendgrid" to use for this feature
- [ ] We should implement generating logs -> can be a log file 
- [ ] We should implement generate reports -> this feature allows getting a text document from a table. He mentioned java script table reports
- [ ] The sales,orders and inventory need an editable list view for list of materials/bom
