### ISSUE TITLE
Finishing up Sprint 4

### ISSUE THREAD

**Issue by obonobo** [serum-390/soen390-team16-godzilla#212]
Check out the reviews from Sprint 2 and 3:

- https://github.com/serum-390/soen390-team16-godzilla/wiki/Sprint-2-Evaluation
- https://github.com/serum-390/soen390-team16-godzilla/wiki/Sprint-3-Evaluation

- [ ] Bookmarks

FROM SPRINT 3
SAD Document:
- [ ] The domain model seems to be incomplete/not include the useful information (no package information). There is no description for the domain model. Ref
- [ ] The class diagram should be in the Development view. The description is too general
- [x] Incorrect diagram label (2 Figure 13)
- [ ] The first Figure 13, no explanation for Elastic container service cluster. Is this specific for AWS, or it's a common service that has a different name in AWS? This diagram should be in the Deployment view
- [x] The second Figure 13, no server information in the Deployment diagram. There is no description too.
- [x] The Package diagram should be in the logical view.
- [ ] The sequence diagrams seem to be incorrect (the lifetime of the process)
- [ ] Wrong notation for Use-case diagrams
- [x] Why 3.10 sources in Bibliography section

FROM SPRINT 2
SAD Document:
- [x] Weird format in ToC
- [ ] Weird format throughout the documents. Your team needs to be more careful before submitting the document.
- [ ] The domain model seems to be incomplete/not include the useful information (no package information). There is no description for the domain model.
- [ ] The class diagram should be in the Development view. The description is too general
- [x] Incorrect diagram label (2 Figure 13)
- [ ] The first Figure 13, no explanation for Elastic container service cluster. Is this specific for AWS, or it's a common service that has a different name in AWS? This diagram should be in the Deployment view
- [ ] The second Figure 13, no server information in the Deployment diagram. There is no description too.
- [x] The Package diagram should be in the logical view.
- [ ] The sequence diagrams seem to be incorrect (the lifetime of the process)
- [ ] Wrong notation for Use-case diagrams
- [x] Why 3.10 sources in Bibliography section

FROM SPRINT 3
Risk Management Plan
- [x] The revision number seems inconsistent with the tagged use (v1.1). I don't understand what is late Version 11/30/06
- [x] There are 2 table 3.
- [x] The second table 3 should be on a single page.
- [x] The list of risks should be in a separate document, preferably Excel or OpenDocument Spreadsheet format.

FROM SPRINT 2
Risk Management Plan
- [x] The revision number seems inconsistent with the tagged use (v1.1). I don't understand what is late Version 11/30/06
- [x] Table 3 should be on a single page
- [x] The list of risks should be in a separate document, preferably Excel or OpenDocument Spreadsheet format.

FROM SPRINT 2+3
Test Plan
- [x] Version is still 1.0
- [ ] Extremely high code coverage planned. You need to make sure you can achieve this target when submitting your deliverable.

**Comment by shushengfuqin** [comment]
- [ ] Quality reports (code quality measurement trends, quality management report)

- [ ]  Release Plan (Sprint #4 planning)

- [ ] UI modeling of Sprint #4 user stories

- [ ] Updated deliverables: SAD, USB, Testing plan and Test Summary Report, defects tracking report, RMP
- [ ] Updated/Changed User Stories + Risks: 2 points 1 point
- [ ] Updated Software Architecture: 2 points 1 point (Class diagram)

- [ ]  Release Plan for Sprint #5: 2 points 1 point

- [ ]  Testing Report: 2 points 1 point (unit tests for the implemented code)

- [ ] Updates on the UI Prototypes based on project owner feedback + New UI prototypes: 3 points 2 point

- [ ] Software Implementation of planned user stories + Bug reports/fixing: 5 points
